import numpy as np
import pytest

from twin.rc_model import RCThermalZone, RCParams, fit_rc_params
from twin.env import CoolTwinEnv


def test_zone_reaches_equilibrium_with_constant_outdoor_temp():
    """With no HVAC/gains and constant outdoor temp, indoor temp should
    converge toward outdoor temp over a long enough horizon."""
    zone = RCThermalZone(RCParams())
    n = 500
    T_out = np.full(n, 25.0)
    Q_hvac = np.zeros(n)
    Q_gain = np.zeros(n)

    traj = zone.simulate(T_out, Q_hvac, Q_gain, T_wall0=15.0, T_in0=15.0, dt_seconds=900)
    T_in_final = traj[-1, 1]

    assert abs(T_in_final - 25.0) < 1.0


def test_cooling_reduces_final_temperature():
    zone = RCThermalZone(RCParams())
    n = 96
    T_out = np.full(n, 30.0)
    Q_gain = np.full(n, 200.0)

    no_cool = zone.simulate(T_out, np.zeros(n), Q_gain, T_wall0=28, T_in0=28)
    with_cool = zone.simulate(T_out, np.full(n, -1500.0), Q_gain, T_wall0=28, T_in0=28)

    assert with_cool[-1, 1] < no_cool[-1, 1]


def test_fit_rc_params_recovers_reasonable_values():
    """Fit against data generated by a known ground-truth parameter set and
    check the fitted params produce a similarly-behaving model (not
    necessarily identical params -- RC systems can be non-identifiable --
    but the resulting trajectory should closely match)."""
    true_params = RCParams(R_out_wall=1.5e-3, R_wall_in=0.8e-3, R_in_out=4e-3, C_wall=4e6, C_in=4e5)
    zone_true = RCThermalZone(true_params)

    n = 96
    rng = np.random.default_rng(0)
    T_out = 24 + 6 * np.sin(np.linspace(0, 2 * np.pi, n)) + rng.normal(0, 0.2, n)
    Q_hvac = rng.uniform(-1000, 1000, n)
    Q_gain = rng.uniform(0, 300, n)

    traj_true = zone_true.simulate(T_out, Q_hvac, Q_gain, T_wall0=22, T_in0=22)
    T_in_ground_truth = traj_true[1:, 1]

    fitted = fit_rc_params(T_out, Q_hvac, Q_gain, T_in_ground_truth,
                            initial_guess=RCParams())  # deliberately different init
    zone_fitted = RCThermalZone(fitted)
    traj_fitted = zone_fitted.simulate(T_out, Q_hvac, Q_gain, T_wall0=22, T_in0=22)

    rmse = np.sqrt(np.mean((traj_fitted[1:, 1] - T_in_ground_truth) ** 2))
    assert rmse < 0.5  # fitted model should track ground truth closely


def test_env_runs_full_episode():
    env = CoolTwinEnv(episode_hours=24, seed=0)
    obs, _ = env.reset(seed=0)
    assert env.observation_space.contains(obs)

    terminated = truncated = False
    steps = 0
    while not (terminated or truncated):
        action = env.action_space.sample()
        obs, reward, terminated, truncated, info = env.step(action)
        assert np.isfinite(reward)
        steps += 1

    assert steps == env.n_steps


def test_env_comfort_penalty_only_when_occupied():
    env = CoolTwinEnv(episode_hours=1, seed=0)
    env.reset(seed=0)
    env.T_in = 40.0  # force an extreme discomfort scenario
    env.t = 0  # hour 0 -> unoccupied per _occupancy()
    _, _, _, _, info = env.step(np.array([0.0], dtype=np.float32))
    assert info["discomfort"] == 0.0
